
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Raiswa
 */
public class bagianRegister extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bagianRegister.class.getName());

    /**
     * Creates new form bagianRegister
     */
    public bagianRegister() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel2 = new javax.swing.JLabel();
        cbShowpassRegis = new javax.swing.JCheckBox();
        regisButton = new javax.swing.JButton();
        txtPasswordRegis = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        labelRegis = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 98, -1, -1));

        cbShowpassRegis.setForeground(new java.awt.Color(255, 255, 255));
        cbShowpassRegis.setText("Show Password");
        cbShowpassRegis.addActionListener(this::cbShowpassRegisActionPerformed);
        getContentPane().add(cbShowpassRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 148, -1, -1));

        regisButton.setText("Register");
        regisButton.addActionListener(this::regisButtonActionPerformed);
        getContentPane().add(regisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 180, 248, -1));
        getContentPane().add(txtPasswordRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 120, 248, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sudah punya akun?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 209, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 48, -1, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 70, 248, -1));

        labelRegis.setForeground(new java.awt.Color(255, 255, 255));
        labelRegis.setText("Login");
        labelRegis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegisMouseClicked(evt);
            }
        });
        getContentPane().add(labelRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 209, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1688918606964248.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbShowpassRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowpassRegisActionPerformed
        if(cbShowpassRegis.isSelected()){
            txtPasswordRegis.setEchoChar((char)0);
        }else{
            txtPasswordRegis.setEchoChar('*');
        }
    }//GEN-LAST:event_cbShowpassRegisActionPerformed

    private void regisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisButtonActionPerformed
       try{
           String sql = "INSERT INTO users(username,password) values (?,?)";
           
           PreparedStatement ps = Koneksi.getConnection().prepareStatement(sql);
           
           ps.setString(1, txtUsername.getText());
           ps.setString(2, String.valueOf(txtPasswordRegis.getPassword()));
           ps.executeUpdate();
           
           JOptionPane.showMessageDialog(this, "registrasi berhasil");
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage());
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_regisButtonActionPerformed

    private void labelRegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegisMouseClicked
bagianLogin reg = new bagianLogin();
    reg.setVisible(true);
    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_labelRegisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bagianRegister().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbShowpassRegis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelRegis;
    private javax.swing.JButton regisButton;
    private javax.swing.JPasswordField txtPasswordRegis;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
