/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Raiswa
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
public class fromPembayaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fromPembayaran.class.getName());

    /**
     * Creates new form fromPembayaran
     */
    
    private String nama;
    private String asal;
    private String tujuan;
    private java.sql.Date tanggal;
    private int jumlah;
    private int totalHarga;
    
    public fromPembayaran() {
    initComponents();
    setLocationRelativeTo(null);
    setupRadioButton();
  
}
    
    public fromPembayaran( String nama, String asal, String tujuan, java.sql.Date tanggal, int jumlah, int totalHarga){
        initComponents();
        setLocationRelativeTo(null);
        
        labelNama.setText("Nama :" + nama);
        labelAsal.setText("Asal :" +asal);
        labelTujuan.setText("Tujuan :" + tujuan);
        labelTanggal.setText("Tanggal :" + tanggal);
        labelJumlahTiket.setText("Jumlah Tiket :" + String.valueOf(jumlah));
        labelHarga.setText("Rp." + totalHarga);
        
        this.nama = nama;
        this.asal = asal;
        this.tujuan = tujuan;
        this.tanggal = tanggal;
        this.jumlah = jumlah;
        this.totalHarga = totalHarga;
        
        setupRadioButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelAsal = new javax.swing.JLabel();
        labelTujuan = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        labelJumlahTiket = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("formPembayaran");
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 239, 232));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("RINGKASAN PESANAN");

        labelNama.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelNama.setText("Nama");

        labelAsal.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelAsal.setText("Asal");

        labelTujuan.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelTujuan.setText("Tujuan");

        labelHarga.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelHarga.setText("Harga");

        labelJumlahTiket.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelJumlahTiket.setText("Jumlah tiket");

        labelTanggal.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        labelTanggal.setText("Tanggal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(labelNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAsal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTujuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelJumlahTiket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTanggal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(labelNama)
                .addGap(18, 18, 18)
                .addComponent(labelAsal)
                .addGap(18, 18, 18)
                .addComponent(labelTujuan)
                .addGap(18, 18, 18)
                .addComponent(labelHarga)
                .addGap(18, 18, 18)
                .addComponent(labelJumlahTiket)
                .addGap(18, 18, 18)
                .addComponent(labelTanggal)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 310));

        jPanel2.setBackground(new java.awt.Color(241, 239, 232));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Pilih Metode Pembayaran");

        jRadioButton1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jRadioButton1.setText("Transfer Bank");

        jRadioButton2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jRadioButton2.setText("E - Wallet");
        jRadioButton2.addActionListener(this::jRadioButton2ActionPerformed);

        jRadioButton3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jRadioButton3.setText("QRIS");

        jButton1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton1.setText("Bayar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 160, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Gemini_Generated_Image_x2o71cx2o71cx2o7.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupRadioButton() {
    javax.swing.ButtonGroup bg = new javax.swing.ButtonGroup();

    bg.add(jRadioButton1);
    bg.add(jRadioButton2);
    bg.add(jRadioButton3);

    jRadioButton1.setText("Transfer Bank");
    jRadioButton2.setText("E-Wallet");
    jRadioButton3.setText("QRIS");
}
    
    
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String metode = "";

    if(jRadioButton1.isSelected()){
        metode = "Transfer Bank";
    }else if(jRadioButton2.isSelected()){
        metode = "E-Wallet";
    }else if(jRadioButton3.isSelected()){
        metode = "QRIS";
    }else{
        JOptionPane.showMessageDialog(this,
                "Pilih metode pembayaran");
        return;
    }
    
    try{

        Connection conn = Koneksi.getConnection();

        String sql = "INSERT INTO pembayaran " + "(nama, asal, tujuan, tanggal_berangkat, jumlah_tiket, total_harga, metode) "
+ "VALUES (?, ?, ?, ?, ?, ?, ?)";
        
        PreparedStatement ps = conn.prepareStatement(sql);

    ps.setString(1, nama);
    ps.setString(2, asal);
    ps.setString(3, tujuan);
    ps.setDate(4, tanggal);
    ps.setInt(5, jumlah);
    ps.setInt(6, totalHarga);
    ps.setString(7, metode);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Pembayaran Berhasil");

        dispose();

    }catch(Exception e){
        JOptionPane.showMessageDialog(this,
                e.getMessage());
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fromPembayaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel labelAsal;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelJumlahTiket;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelTujuan;
    // End of variables declaration//GEN-END:variables
}
